In [3]:
# Cell 0 — Install dependencies (run once)
import subprocess
subprocess.run(["pip3", "install", "sqlalchemy", "psycopg2-binary", "--quiet"], check=True)
print("Done.")

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

Done.

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.

In [4]:
# Cell 1 — Imports and connection
import pandas as pd
import sqlalchemy as sa
from IPython.display import display

pd.set_option("display.max_rows", 300)
pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", 60)

ENGINE = sa.create_engine(
    "postgresql+psycopg2://postgres:postgres@127.0.0.1:5455/postgres"
)

def q(sql, **kwargs):
    with ENGINE.connect() as con:
        return pd.read_sql(sa.text(sql), con, **kwargs)

print("Connected.")

Connected.

In [5]:
# Cell 2 — Q1: Raw column inventory (information_schema)
# ─────────────────────────────────────────────────────────
# List every column in every table in the int schema.
# Do NOT hardcode table names — drive everything from information_schema.

raw_inventory = q("""
    SELECT
        table_name,
        column_name,
        data_type,
        ordinal_position
    FROM information_schema.columns
    WHERE table_schema = 'int'
    ORDER BY table_name, ordinal_position
""")

print(f"Total columns across all int tables: {len(raw_inventory)}")
print(f"Tables found: {sorted(raw_inventory['table_name'].unique())}\n")
display(raw_inventory.drop(columns="ordinal_position"))

Total columns across all int tables: 235
Tables found: ['int_game_environment', 'int_game_team_features', 'int_team_season_context', 'int_team_season_features', 'venue_elevations']

                   table_name                         column_name         data_type
0        int_game_environment                             game_id            bigint
1        int_game_environment                              season           integer
2        int_game_environment                                week           integer
3        int_game_environment                           home_team              text
4        int_game_environment                           away_team              text
5        int_game_environment                            venue_id            bigint
6        int_game_environment                             is_dome           boolean
7        int_game_environment                  venue_elevation_ft  double precision
8        int_game_environment              away_home_elevation_ft  double precision
9        int_game_environment             away_elevation_delta_ft  double precision
10       int_game_environment            away_elevation_ascent_ft  double precision
11       int_game_environment             away_travel_distance_mi           numeric
12       int_game_environment                   away_tz_delta_hrs           integer
13       int_game_environment                       temperature_f           numeric
14       int_game_environment                      wind_speed_mph           numeric
15       int_game_environment                      wind_gusts_mph           numeric
16       int_game_environment                precipitation_inches           numeric
17       int_game_environment                        humidity_pct          smallint
18       int_game_environment                        is_high_wind           boolean
19       int_game_environment                    is_precipitation           boolean
20       int_game_environment            is_dome_adjusted_weather           boolean
21     int_game_team_features                             game_id            bigint
22     int_game_team_features                              season           integer
23     int_game_team_features                                week           integer
24     int_game_team_features                           game_date              date
25     int_game_team_features                           team_name              text
26     int_game_team_features                            opponent              text
27     int_game_team_features                       points_scored           integer
28     int_game_team_features                      points_allowed           integer
29     int_game_team_features                                 win           integer
30     int_game_team_features                    off_epa_per_play           numeric
31     int_game_team_features            def_epa_per_play_allowed           numeric
32     int_game_team_features             close_game_epa_per_play           numeric
33     int_game_team_features               close_game_play_count            bigint
34     int_game_team_features                         game_script              text
35     int_game_team_features              game_script_avg_margin           numeric
36     int_game_team_features                   last3_off_epa_avg           numeric
37     int_game_team_features                       last3_win_pct           numeric
38     int_game_team_features             last3_points_scored_avg           numeric
39     int_game_team_features                   last3_def_epa_avg           numeric
40     int_game_team_features            last3_points_allowed_avg           numeric
41     int_game_team_features                days_since_last_game           integer
42     int_game_team_features          opp_sp_rating_at_game_time           numeric
43    int_team_season_context                           team_name              text
44    int_team_season_context                              season           integer
45    int_team_season_context                          conference              text
46    int_team_season_context                    off_epa_per_play           numeric
47    int_team_season_context                       off_epa_total           numeric
48    int_team_season_context                     off_passing_epa           numeric
49    int_team_season_context                     off_rushing_epa           numeric
50    int_team_season_context                    off_success_rate           numeric
51    int_team_season_context               off_pass_success_rate           numeric
52    int_team_season_context               off_rush_success_rate           numeric
53    int_team_season_context                   off_explosiveness           numeric
54    int_team_season_context          off_std_downs_success_rate           numeric
55    int_team_season_context         off_pass_downs_success_rate           numeric
56    int_team_season_context                   off_std_downs_epa           numeric
57    int_team_season_context                  off_pass_downs_epa           numeric
58    int_team_season_context                      plays_per_game           numeric
59    int_team_season_context              off_epa_total_per_game           numeric
60    int_team_season_context            scoring_efficiency_ratio           numeric
61    int_team_season_context                           rush_rate           numeric
62    int_team_season_context                   off_power_success           numeric
63    int_team_season_context                      off_stuff_rate           numeric
64    int_team_season_context                      off_line_yards           numeric
65    int_team_season_context              off_second_level_yards           numeric
66    int_team_season_context                off_open_field_yards           numeric
67    int_team_season_context                     off_pts_per_opp           numeric
68    int_team_season_context                    def_epa_per_play           numeric
69    int_team_season_context                       def_epa_total           numeric
70    int_team_season_context                     def_passing_epa           numeric
71    int_team_season_context                     def_rushing_epa           numeric
72    int_team_season_context                    def_success_rate           numeric
73    int_team_season_context               def_pass_success_rate           numeric
74    int_team_season_context               def_rush_success_rate           numeric
75    int_team_season_context                   def_explosiveness           numeric
76    int_team_season_context          def_std_downs_success_rate           numeric
77    int_team_season_context         def_pass_downs_success_rate           numeric
78    int_team_season_context                   def_std_downs_epa           numeric
79    int_team_season_context                  def_pass_downs_epa           numeric
80    int_team_season_context                   def_power_success           numeric
81    int_team_season_context                      def_stuff_rate           numeric
82    int_team_season_context                      def_line_yards           numeric
83    int_team_season_context              def_second_level_yards           numeric
84    int_team_season_context                def_open_field_yards           numeric
85    int_team_season_context                     def_pts_per_opp           numeric
86    int_team_season_context                     def_havoc_total           numeric
87    int_team_season_context               def_havoc_front_seven           numeric
88    int_team_season_context                        def_havoc_db           numeric
89    int_team_season_context                      sacks_per_game           numeric
90    int_team_season_context                        tfl_per_game           numeric
91    int_team_season_context            off_third_down_conv_rate           numeric
92    int_team_season_context                    epa_differential           numeric
93    int_team_season_context        off_field_position_avg_start           numeric
94    int_team_season_context        def_field_position_avg_start           numeric
95    int_team_season_context    off_field_position_predicted_pts           numeric
96    int_team_season_context    def_field_position_predicted_pts           numeric
97    int_team_season_context           turnovers_forced_per_game           numeric
98    int_team_season_context             turnovers_lost_per_game           numeric
99    int_team_season_context            turnover_margin_per_game           numeric
100   int_team_season_context                  penalties_per_game           numeric
101   int_team_season_context              penalty_yards_per_game           numeric
102   int_team_season_context                        games_played            bigint
103   int_team_season_context                                wins            bigint
104   int_team_season_context                              losses            bigint
105   int_team_season_context                             win_pct           numeric
106   int_team_season_context                   avg_points_scored           numeric
107   int_team_season_context                  avg_points_allowed           numeric
108   int_team_season_context                      avg_point_diff           numeric
109   int_team_season_context                          home_games            bigint
110   int_team_season_context                          away_games            bigint
111   int_team_season_context                  neutral_site_games            bigint
112   int_team_season_context                           sp_rating           numeric
113   int_team_season_context                          sp_ranking           integer
114   int_team_season_context                          sp_offense           numeric
115   int_team_season_context                          sp_defense           numeric
116   int_team_season_context                    sp_special_teams           numeric
117   int_team_season_context                  sp_offense_ranking           integer
118   int_team_season_context                  sp_defense_ranking           integer
119   int_team_season_context                  recruiting_3yr_avg           numeric
120   int_team_season_context                  current_class_rank           integer
121   int_team_season_context                  pct_games_dominant           numeric
122   int_team_season_context               pct_games_comfortable           numeric
123   int_team_season_context               pct_games_competitive           numeric
124   int_team_season_context                   pct_games_deficit           numeric
125   int_team_season_context             pct_games_large_deficit           numeric
126   int_team_season_context  close_game_epa_per_play_season_avg           numeric
127   int_team_season_context              close_game_plays_total           numeric
128   int_team_season_context                    close_game_count            bigint
129   int_team_season_context        close_game_count_plays_based            bigint
130  int_team_season_features                           team_name              text
131  int_team_season_features                              season           integer
132  int_team_season_features                             team_id           integer
133  int_team_season_features                          conference              text
134  int_team_season_features                                city              text
135  int_team_season_features                               state              text
136  int_team_season_features                            latitude           numeric
137  int_team_season_features                           longitude           numeric
138  int_team_season_features                            timezone              text
139  int_team_season_features                        games_played            bigint
140  int_team_season_features                                wins            bigint
141  int_team_season_features                              losses            bigint
142  int_team_season_features                             win_pct           numeric
143  int_team_season_features                   avg_points_scored           numeric
144  int_team_season_features                  avg_points_allowed           numeric
145  int_team_season_features                      avg_point_diff           numeric
146  int_team_season_features                          home_games            bigint
147  int_team_season_features                          away_games            bigint
148  int_team_season_features                  neutral_site_games            bigint
149  int_team_season_features                           sp_rating           numeric
150  int_team_season_features                          sp_ranking           integer
151  int_team_season_features                          sp_offense           numeric
152  int_team_season_features                          sp_defense           numeric
153  int_team_season_features                    sp_special_teams           numeric
154  int_team_season_features                  sp_offense_ranking           integer
155  int_team_season_features                  sp_defense_ranking           integer
156  int_team_season_features                    off_epa_per_play           numeric
157  int_team_season_features                       off_epa_total           numeric
158  int_team_season_features                     off_passing_epa           numeric
159  int_team_season_features                     off_rushing_epa           numeric
160  int_team_season_features                    def_epa_per_play           numeric
161  int_team_season_features                       def_epa_total           numeric
162  int_team_season_features                     def_passing_epa           numeric
163  int_team_season_features                     def_rushing_epa           numeric
164  int_team_season_features                    epa_differential           numeric
165  int_team_season_features                    off_success_rate           numeric
166  int_team_season_features               off_pass_success_rate           numeric
167  int_team_season_features               off_rush_success_rate           numeric
168  int_team_season_features          off_std_downs_success_rate           numeric
169  int_team_season_features         off_pass_downs_success_rate           numeric
170  int_team_season_features                    def_success_rate           numeric
171  int_team_season_features               def_pass_success_rate           numeric
172  int_team_season_features               def_rush_success_rate           numeric
173  int_team_season_features          def_std_downs_success_rate           numeric
174  int_team_season_features         def_pass_downs_success_rate           numeric
175  int_team_season_features                   off_std_downs_epa           numeric
176  int_team_season_features                  off_pass_downs_epa           numeric
177  int_team_season_features                   def_std_downs_epa           numeric
178  int_team_season_features                  def_pass_downs_epa           numeric
179  int_team_season_features                   off_explosiveness           numeric
180  int_team_season_features                   def_explosiveness           numeric
181  int_team_season_features                   off_power_success           numeric
182  int_team_season_features                      off_stuff_rate           numeric
183  int_team_season_features                      off_line_yards           numeric
184  int_team_season_features              off_second_level_yards           numeric
185  int_team_season_features                off_open_field_yards           numeric
186  int_team_season_features                   def_power_success           numeric
187  int_team_season_features                      def_stuff_rate           numeric
188  int_team_season_features                      def_line_yards           numeric
189  int_team_season_features              def_second_level_yards           numeric
190  int_team_season_features                def_open_field_yards           numeric
191  int_team_season_features                     off_pts_per_opp           numeric
192  int_team_season_features                     def_pts_per_opp           numeric
193  int_team_season_features        off_field_position_avg_start           numeric
194  int_team_season_features        def_field_position_avg_start           numeric
195  int_team_season_features    off_field_position_predicted_pts           numeric
196  int_team_season_features    def_field_position_predicted_pts           numeric
197  int_team_season_features                     def_havoc_total           numeric
198  int_team_season_features               def_havoc_front_seven           numeric
199  int_team_season_features                        def_havoc_db           numeric
200  int_team_season_features                           off_plays           integer
201  int_team_season_features                          off_drives           integer
202  int_team_season_features                           def_plays           integer
203  int_team_season_features                          def_drives           integer
204  int_team_season_features                          stat_games           integer
205  int_team_season_features                       pass_attempts           integer
206  int_team_season_features                    pass_completions           integer
207  int_team_season_features                       passing_yards           numeric
208  int_team_season_features                            pass_tds           integer
209  int_team_season_features                interceptions_thrown           integer
210  int_team_season_features                       rush_attempts           integer
211  int_team_season_features                       rushing_yards           numeric
212  int_team_season_features                            rush_tds           integer
213  int_team_season_features                 third_down_attempts           integer
214  int_team_season_features              third_down_conversions           integer
215  int_team_season_features                fourth_down_attempts           integer
216  int_team_season_features             fourth_down_conversions           integer
217  int_team_season_features                           penalties           integer
218  int_team_season_features                       penalty_yards           numeric
219  int_team_season_features                        fumbles_lost           integer
220  int_team_season_features                   fumbles_recovered           integer
221  int_team_season_features                interceptions_gained           integer
222  int_team_season_features                           turnovers           integer
223  int_team_season_features                               sacks           integer
224  int_team_season_features                    tackles_for_loss           integer
225  int_team_season_features                         total_yards           numeric
226  int_team_season_features                      completion_pct           numeric
227  int_team_season_features                   yards_per_attempt           numeric
228  int_team_season_features                      third_down_pct           numeric
229  int_team_season_features                     fourth_down_pct           numeric
230  int_team_season_features                  recruiting_3yr_avg           numeric
231  int_team_season_features                  current_class_rank           integer
232          venue_elevations                            venue_id           integer
233          venue_elevations                          venue_name              text
234          venue_elevations                      elevation_feet  double precision

In [6]:
# Cell 3 — Q2: Columns duplicated across tables
# ──────────────────────────────────────────────
# A column is "duplicated" if the same column_name appears in two or more
# distinct int tables. List each duplicated name and every table it lives in.

dup_counts = (
    raw_inventory
    .groupby("column_name")["table_name"]
    .nunique()
    .reset_index(name="table_count")
)

duplicated_names = dup_counts.loc[dup_counts["table_count"] >= 2, "column_name"].tolist()

dups = (
    raw_inventory
    .loc[raw_inventory["column_name"].isin(duplicated_names),
         ["column_name", "table_name", "data_type"]]
    .sort_values(["column_name", "table_name"])
    .reset_index(drop=True)
)

print(f"Distinct column names appearing in ≥2 tables: {len(duplicated_names)}")
print()
display(dups)

Distinct column names appearing in ≥2 tables: 69

                          column_name                table_name data_type
0                      avg_point_diff   int_team_season_context   numeric
1                      avg_point_diff  int_team_season_features   numeric
2                  avg_points_allowed   int_team_season_context   numeric
3                  avg_points_allowed  int_team_season_features   numeric
4                   avg_points_scored   int_team_season_context   numeric
5                   avg_points_scored  int_team_season_features   numeric
6                          away_games   int_team_season_context    bigint
7                          away_games  int_team_season_features    bigint
8                          conference   int_team_season_context      text
9                          conference  int_team_season_features      text
10                 current_class_rank   int_team_season_context   integer
11                 current_class_rank  int_team_season_features   integer
12                   def_epa_per_play   int_team_season_context   numeric
13                   def_epa_per_play  int_team_season_features   numeric
14                      def_epa_total   int_team_season_context   numeric
15                      def_epa_total  int_team_season_features   numeric
16                  def_explosiveness   int_team_season_context   numeric
17                  def_explosiveness  int_team_season_features   numeric
18       def_field_position_avg_start   int_team_season_context   numeric
19       def_field_position_avg_start  int_team_season_features   numeric
20   def_field_position_predicted_pts   int_team_season_context   numeric
21   def_field_position_predicted_pts  int_team_season_features   numeric
22                       def_havoc_db   int_team_season_context   numeric
23                       def_havoc_db  int_team_season_features   numeric
24              def_havoc_front_seven   int_team_season_context   numeric
25              def_havoc_front_seven  int_team_season_features   numeric
26                    def_havoc_total   int_team_season_context   numeric
27                    def_havoc_total  int_team_season_features   numeric
28                     def_line_yards   int_team_season_context   numeric
29                     def_line_yards  int_team_season_features   numeric
30               def_open_field_yards   int_team_season_context   numeric
31               def_open_field_yards  int_team_season_features   numeric
32                 def_pass_downs_epa   int_team_season_context   numeric
33                 def_pass_downs_epa  int_team_season_features   numeric
34        def_pass_downs_success_rate   int_team_season_context   numeric
35        def_pass_downs_success_rate  int_team_season_features   numeric
36              def_pass_success_rate   int_team_season_context   numeric
37              def_pass_success_rate  int_team_season_features   numeric
38                    def_passing_epa   int_team_season_context   numeric
39                    def_passing_epa  int_team_season_features   numeric
40                  def_power_success   int_team_season_context   numeric
41                  def_power_success  int_team_season_features   numeric
42                    def_pts_per_opp   int_team_season_context   numeric
43                    def_pts_per_opp  int_team_season_features   numeric
44              def_rush_success_rate   int_team_season_context   numeric
45              def_rush_success_rate  int_team_season_features   numeric
46                    def_rushing_epa   int_team_season_context   numeric
47                    def_rushing_epa  int_team_season_features   numeric
48             def_second_level_yards   int_team_season_context   numeric
49             def_second_level_yards  int_team_season_features   numeric
50                  def_std_downs_epa   int_team_season_context   numeric
51                  def_std_downs_epa  int_team_season_features   numeric
52         def_std_downs_success_rate   int_team_season_context   numeric
53         def_std_downs_success_rate  int_team_season_features   numeric
54                     def_stuff_rate   int_team_season_context   numeric
55                     def_stuff_rate  int_team_season_features   numeric
56                   def_success_rate   int_team_season_context   numeric
57                   def_success_rate  int_team_season_features   numeric
58                   epa_differential   int_team_season_context   numeric
59                   epa_differential  int_team_season_features   numeric
60                            game_id      int_game_environment    bigint
61                            game_id    int_game_team_features    bigint
62                       games_played   int_team_season_context    bigint
63                       games_played  int_team_season_features    bigint
64                         home_games   int_team_season_context    bigint
65                         home_games  int_team_season_features    bigint
66                             losses   int_team_season_context    bigint
67                             losses  int_team_season_features    bigint
68                 neutral_site_games   int_team_season_context    bigint
69                 neutral_site_games  int_team_season_features    bigint
70                   off_epa_per_play    int_game_team_features   numeric
71                   off_epa_per_play   int_team_season_context   numeric
72                   off_epa_per_play  int_team_season_features   numeric
73                      off_epa_total   int_team_season_context   numeric
74                      off_epa_total  int_team_season_features   numeric
75                  off_explosiveness   int_team_season_context   numeric
76                  off_explosiveness  int_team_season_features   numeric
77       off_field_position_avg_start   int_team_season_context   numeric
78       off_field_position_avg_start  int_team_season_features   numeric
79   off_field_position_predicted_pts   int_team_season_context   numeric
80   off_field_position_predicted_pts  int_team_season_features   numeric
81                     off_line_yards   int_team_season_context   numeric
82                     off_line_yards  int_team_season_features   numeric
83               off_open_field_yards   int_team_season_context   numeric
84               off_open_field_yards  int_team_season_features   numeric
85                 off_pass_downs_epa   int_team_season_context   numeric
86                 off_pass_downs_epa  int_team_season_features   numeric
87        off_pass_downs_success_rate   int_team_season_context   numeric
88        off_pass_downs_success_rate  int_team_season_features   numeric
89              off_pass_success_rate   int_team_season_context   numeric
90              off_pass_success_rate  int_team_season_features   numeric
91                    off_passing_epa   int_team_season_context   numeric
92                    off_passing_epa  int_team_season_features   numeric
93                  off_power_success   int_team_season_context   numeric
94                  off_power_success  int_team_season_features   numeric
95                    off_pts_per_opp   int_team_season_context   numeric
96                    off_pts_per_opp  int_team_season_features   numeric
97              off_rush_success_rate   int_team_season_context   numeric
98              off_rush_success_rate  int_team_season_features   numeric
99                    off_rushing_epa   int_team_season_context   numeric
100                   off_rushing_epa  int_team_season_features   numeric
101            off_second_level_yards   int_team_season_context   numeric
102            off_second_level_yards  int_team_season_features   numeric
103                 off_std_downs_epa   int_team_season_context   numeric
104                 off_std_downs_epa  int_team_season_features   numeric
105        off_std_downs_success_rate   int_team_season_context   numeric
106        off_std_downs_success_rate  int_team_season_features   numeric
107                    off_stuff_rate   int_team_season_context   numeric
108                    off_stuff_rate  int_team_season_features   numeric
109                  off_success_rate   int_team_season_context   numeric
110                  off_success_rate  int_team_season_features   numeric
111                recruiting_3yr_avg   int_team_season_context   numeric
112                recruiting_3yr_avg  int_team_season_features   numeric
113                            season      int_game_environment   integer
114                            season    int_game_team_features   integer
115                            season   int_team_season_context   integer
116                            season  int_team_season_features   integer
117                        sp_defense   int_team_season_context   numeric
118                        sp_defense  int_team_season_features   numeric
119                sp_defense_ranking   int_team_season_context   integer
120                sp_defense_ranking  int_team_season_features   integer
121                        sp_offense   int_team_season_context   numeric
122                        sp_offense  int_team_season_features   numeric
123                sp_offense_ranking   int_team_season_context   integer
124                sp_offense_ranking  int_team_season_features   integer
125                        sp_ranking   int_team_season_context   integer
126                        sp_ranking  int_team_season_features   integer
127                         sp_rating   int_team_season_context   numeric
128                         sp_rating  int_team_season_features   numeric
129                  sp_special_teams   int_team_season_context   numeric
130                  sp_special_teams  int_team_season_features   numeric
131                         team_name    int_game_team_features      text
132                         team_name   int_team_season_context      text
133                         team_name  int_team_season_features      text
134                          venue_id      int_game_environment    bigint
135                          venue_id          venue_elevations   integer
136                              week      int_game_environment   integer
137                              week    int_game_team_features   integer
138                           win_pct   int_team_season_context   numeric
139                           win_pct  int_team_season_features   numeric
140                              wins   int_team_season_context    bigint
141                              wins  int_team_season_features    bigint

In [7]:
# Cell 4 — Q3: Authoritative-source rulings
# ──────────────────────────────────────────
# Rules applied in priority order:
#   R1. JOIN KEY  — game_id, team_id, season, week, home_team, away_team,
#                   opponent_id, game_date.  Flag as join key; every table
#                   may hold it; not a feature candidate.
#   R2. FEATURE TABLE > STAGING PASS-THROUGH
#       Tables classified as staging pass-throughs (int_games, int_teams,
#       int_team_game_stats) hold raw/minimally-processed values.
#       Derived feature tables (int_team_game_features, int_team_season_features,
#       int_team_season_context) are authoritative when both are present.
#   R3. GAME-LEVEL > SEASON-LEVEL  (more granular wins for game-level modeling)
#       If both a *_game_* and a *_season_* table hold the column,
#       the game-level table is authoritative.
#   R4. CONTEXT TABLE  — int_team_season_context holds opponent/schedule
#       context that does not exist elsewhere; it is authoritative for
#       those columns even against int_team_season_features.
#
# For each duplicated column: state authoritative table, reason, and
# disposition of every non-authoritative copy.

# ── Table classification ──────────────────────────────────────────────────
TABLE_TIER = {
    # staging / raw pass-throughs
    "int_games":              "staging",
    "int_teams":              "staging",
    "int_team_game_stats":    "staging",
    # derived feature tables (game-level)
    "int_team_game_features": "feature_game",
    # derived feature tables (season-level)
    "int_team_season_features": "feature_season",
    "int_team_season_context":  "feature_season",
}

# Key columns that are join keys, not features
JOIN_KEYS = {
    "game_id", "team_id", "season", "week",
    "home_team", "away_team", "opponent_id",
    "game_date", "start_date",
}

# ── Build rulings ─────────────────────────────────────────────────────────
rulings = []

for col in sorted(duplicated_names):
    tables_with_col = (
        raw_inventory.loc[raw_inventory["column_name"] == col, "table_name"]
        .tolist()
    )
    dtype = (
        raw_inventory.loc[raw_inventory["column_name"] == col, "data_type"]
        .iloc[0]
    )

    # R1 — Join key
    if col in JOIN_KEYS:
        for tbl in tables_with_col:
            rulings.append(dict(
                column_name=col,
                table=tbl,
                dtype=dtype,
                disposition="JOIN KEY — present in all tables; not a feature candidate",
                authoritative="ALL (join key)",
                reason="R1: join key",
            ))
        continue

    # Classify each table that has this column
    tiers = {tbl: TABLE_TIER.get(tbl, "unknown") for tbl in tables_with_col}

    # Determine authoritative table
    auth_table = None
    reason = None

    feature_game_tables   = [t for t, v in tiers.items() if v == "feature_game"]
    feature_season_tables = [t for t, v in tiers.items() if v == "feature_season"]
    staging_tables        = [t for t, v in tiers.items() if v == "staging"]

    # R3: prefer game-level feature table if present
    if feature_game_tables:
        auth_table = feature_game_tables[0]
        reason = "R3: game-level feature table preferred over season-level for game-level modeling"
    # R4: context table owns context columns (no game-level alternative)
    elif "int_team_season_context" in feature_season_tables and len(feature_season_tables) == 1:
        auth_table = "int_team_season_context"
        reason = "R4: only season-level home is context table"
    # R2: feature table beats staging
    elif feature_season_tables:
        # if both context and features have it, features wins (richer engineering)
        if "int_team_season_features" in feature_season_tables:
            auth_table = "int_team_season_features"
            reason = "R2: feature table authoritative over staging pass-through"
        else:
            auth_table = feature_season_tables[0]
            reason = "R2: feature table authoritative over staging pass-through"
    elif staging_tables:
        # all copies are staging; pick the one closest to raw (first alphabetically)
        auth_table = sorted(staging_tables)[0]
        reason = "R2-fallback: all copies are staging; earliest alphabetically retained"
    else:
        auth_table = tables_with_col[0]
        reason = "Unknown tier; first table retained by default"

    for tbl in tables_with_col:
        is_auth = (tbl == auth_table)
        if is_auth:
            disposition = "KEEP — authoritative copy"
        else:
            disposition = f"DROP from candidate list — superseded by {auth_table}"
        rulings.append(dict(
            column_name=col,
            table=tbl,
            dtype=dtype,
            disposition=disposition,
            authoritative=auth_table,
            reason=reason,
        ))

rulings_df = pd.DataFrame(rulings)

print("=== Q3 — Authoritative-Source Rulings ===\n")
display(rulings_df)

=== Q3 — Authoritative-Source Rulings ===

,column_name,table,dtype,disposition,authoritative,reason
0,avg_point_diff,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
1,avg_point_diff,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
2,avg_points_allowed,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
3,avg_points_allowed,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
4,avg_points_scored,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
5,avg_points_scored,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
6,away_games,int_team_season_context,bigint,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
7,away_games,int_team_season_features,bigint,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
8,conference,int_team_season_context,text,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
9,conference,int_team_season_features,text,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
10,current_class_rank,int_team_season_context,integer,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
11,current_class_rank,int_team_season_features,integer,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
12,def_epa_per_play,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
13,def_epa_per_play,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
14,def_epa_total,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
15,def_epa_total,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
16,def_explosiveness,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
17,def_explosiveness,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
18,def_field_position_avg_start,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
19,def_field_position_avg_start,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
20,def_field_position_predicted_pts,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
21,def_field_position_predicted_pts,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
22,def_havoc_db,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
23,def_havoc_db,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
24,def_havoc_front_seven,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
25,def_havoc_front_seven,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
26,def_havoc_total,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
27,def_havoc_total,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
28,def_line_yards,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
29,def_line_yards,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
30,def_open_field_yards,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
31,def_open_field_yards,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
32,def_pass_downs_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
33,def_pass_downs_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
34,def_pass_downs_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
35,def_pass_downs_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
36,def_pass_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
37,def_pass_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
38,def_passing_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
39,def_passing_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
40,def_power_success,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
41,def_power_success,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
42,def_pts_per_opp,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
43,def_pts_per_opp,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
44,def_rush_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
45,def_rush_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
46,def_rushing_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
47,def_rushing_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
48,def_second_level_yards,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
49,def_second_level_yards,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
50,def_std_downs_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
51,def_std_downs_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
52,def_std_downs_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
53,def_std_downs_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
54,def_stuff_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
55,def_stuff_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
56,def_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
57,def_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
58,epa_differential,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
59,epa_differential,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
60,game_id,int_game_environment,bigint,JOIN KEY — present in all tables; not a feature candidate,ALL (join key),R1: join key
61,game_id,int_game_team_features,bigint,JOIN KEY — present in all tables; not a feature candidate,ALL (join key),R1: join key
62,games_played,int_team_season_context,bigint,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
63,games_played,int_team_season_features,bigint,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
64,home_games,int_team_season_context,bigint,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
65,home_games,int_team_season_features,bigint,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
66,losses,int_team_season_context,bigint,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
67,losses,int_team_season_features,bigint,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
68,neutral_site_games,int_team_season_context,bigint,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
69,neutral_site_games,int_team_season_features,bigint,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
70,off_epa_per_play,int_game_team_features,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
71,off_epa_per_play,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
72,off_epa_per_play,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
73,off_epa_total,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
74,off_epa_total,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
75,off_explosiveness,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
76,off_explosiveness,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
77,off_field_position_avg_start,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
78,off_field_position_avg_start,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
79,off_field_position_predicted_pts,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
80,off_field_position_predicted_pts,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
81,off_line_yards,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
82,off_line_yards,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
83,off_open_field_yards,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
84,off_open_field_yards,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
85,off_pass_downs_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
86,off_pass_downs_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
87,off_pass_downs_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
88,off_pass_downs_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
89,off_pass_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
90,off_pass_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
91,off_passing_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
92,off_passing_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
93,off_power_success,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
94,off_power_success,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
95,off_pts_per_opp,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
96,off_pts_per_opp,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
97,off_rush_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
98,off_rush_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
99,off_rushing_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
100,off_rushing_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
101,off_second_level_yards,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
102,off_second_level_yards,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
103,off_std_downs_epa,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
104,off_std_downs_epa,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
105,off_std_downs_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
106,off_std_downs_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
107,off_stuff_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
108,off_stuff_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through
109,off_success_rate,int_team_season_context,numeric,DROP from candidate list — superseded by int_team_season...,int_team_season_features,R2: feature table authoritative over staging pass-through
110,off_success_rate,int_team_season_features,numeric,KEEP — authoritative copy,int_team_season_features,R2: feature table authoritative over staging pass-through

In [8]:
# Cell 5 — Q4: Downstream-calculation detection
# ──────────────────────────────────────────────
# Inspect int_team_season_features and int_team_season_context.
# Flag columns that are computable as a ratio, rate, or simple arithmetic
# of other columns present in the SAME table.
#
# Method:
#   1. Pull the actual column names for each table.
#   2. Apply a declarative registry of known derived patterns:
#         derived_col → (numerator_col, denominator_col)  for rates/ratios
#         derived_col → (component_a, component_b, 'sum') for sums
#   3. A column is flagged as downstream if:
#        – it matches a registry entry, AND
#        – all parent columns are present in the same table.
#   4. If the parents are absent, the column is NOT flagged (it may be
#      the most atomic form available).

# ── Fetch column lists ─────────────────────────────────────────────────────
def cols_for_table(tbl):
    return set(
        q("SELECT column_name FROM information_schema.columns "
          "WHERE table_schema = 'int' AND table_name = :t",
          params={"t": tbl})["column_name"].tolist()
    )

feat_cols    = cols_for_table("int_team_season_features")
context_cols = cols_for_table("int_team_season_context")

print(f"int_team_season_features columns : {len(feat_cols)}")
print(f"int_team_season_context  columns : {len(context_cols)}")

int_team_season_features columns : 102
int_team_season_context  columns : 87

In [9]:
# Cell 6 — Derived-column registry and evaluation
# ─────────────────────────────────────────────────
# Each entry: (derived_column, parent_a, parent_b, relationship)
# relationship: 'ratio' | 'sum' | 'difference' | 'product'
# Add rows as you discover new patterns during inspection.

DERIVED_REGISTRY = [
    # ── Passing ───────────────────────────────────────────────────────────
    ("completion_pct",          "completions",          "pass_attempts",        "ratio"),
    ("yards_per_attempt",       "pass_yards",           "pass_attempts",        "ratio"),
    ("yards_per_completion",    "pass_yards",           "completions",          "ratio"),
    ("pass_td_rate",            "pass_tds",             "pass_attempts",        "ratio"),
    ("interception_rate",       "interceptions_thrown", "pass_attempts",        "ratio"),
    ("adj_pass_yards",          "pass_yards",           "yards_after_catch",    "difference"),

    # ── Rushing ───────────────────────────────────────────────────────────
    ("yards_per_carry",         "rush_yards",           "rush_attempts",        "ratio"),
    ("rush_td_rate",            "rush_tds",             "rush_attempts",        "ratio"),
    ("rush_success_rate",       "rush_successes",       "rush_attempts",        "ratio"),

    # ── Scoring / overall offense ─────────────────────────────────────────
    ("points_per_play",         "points",               "total_plays",          "ratio"),
    ("yards_per_play",          "total_yards",          "total_plays",          "ratio"),
    ("scoring_rate",            "points",               "drives",               "ratio"),
    ("yards_per_drive",         "total_yards",          "drives",               "ratio"),
    ("points_per_drive",        "points",               "drives",               "ratio"),
    ("plays_per_drive",         "total_plays",          "drives",               "ratio"),

    # ── Third down ────────────────────────────────────────────────────────
    ("third_down_pct",          "third_down_conversions", "third_down_attempts","ratio"),

    # ── Fourth down ───────────────────────────────────────────────────────
    ("fourth_down_pct",         "fourth_down_conversions","fourth_down_attempts","ratio"),

    # ── Red zone ──────────────────────────────────────────────────────────
    ("red_zone_pct",            "red_zone_scores",      "red_zone_trips",       "ratio"),
    ("red_zone_td_pct",         "red_zone_tds",         "red_zone_trips",       "ratio"),

    # ── Turnovers ─────────────────────────────────────────────────────────
    ("turnover_margin",         "turnovers_forced",     "turnovers_committed",  "difference"),
    ("turnover_rate",           "turnovers_committed",  "total_plays",          "ratio"),

    # ── Defense ───────────────────────────────────────────────────────────
    ("opp_completion_pct",      "opp_completions",      "opp_pass_attempts",    "ratio"),
    ("opp_yards_per_carry",     "opp_rush_yards",       "opp_rush_attempts",    "ratio"),
    ("opp_yards_per_play",      "opp_total_yards",      "opp_total_plays",      "ratio"),
    ("opp_third_down_pct",      "opp_third_down_conversions","opp_third_down_attempts","ratio"),
    ("opp_points_per_drive",    "opp_points",           "opp_drives",           "ratio"),

    # ── Special teams ─────────────────────────────────────────────────────
    ("fg_pct",                  "fg_made",              "fg_attempts",          "ratio"),
    ("kickoff_touchback_pct",   "kickoff_touchbacks",   "kickoffs",             "ratio"),

    # ── Havoc / disruption ────────────────────────────────────────────────
    ("havoc_rate",              "havoc_events",         "opp_total_plays",      "ratio"),
    ("db_havoc_rate",           "db_havoc_events",      "opp_total_plays",      "ratio"),
    ("front_seven_havoc_rate",  "front_seven_havoc_events","opp_total_plays",   "ratio"),

    # ── Context (int_team_season_context) ─────────────────────────────────
    ("avg_opp_sp_rating",       "sum_opp_sp_rating",    "games_played",         "ratio"),
    ("avg_opp_points",          "sum_opp_points",       "games_played",         "ratio"),
    ("home_win_pct",            "home_wins",            "home_games",           "ratio"),
    ("away_win_pct",            "away_wins",            "away_games",           "ratio"),
    ("neutral_win_pct",         "neutral_wins",         "neutral_games",        "ratio"),
    ("conf_win_pct",            "conf_wins",            "conf_games",           "ratio"),
    ("win_pct",                 "wins",                 "games_played",         "ratio"),
]

def evaluate_derived(table_cols, table_label):
    results = []
    for row in DERIVED_REGISTRY:
        derived, parent_a, parent_b, rel = row
        if derived not in table_cols:
            continue  # column doesn't exist in this table — skip
        parents_present = (parent_a in table_cols) and (parent_b in table_cols)
        results.append(dict(
            table=table_label,
            derived_column=derived,
            relationship=rel,
            parent_a=parent_a,
            parent_b=parent_b,
            parents_present=parents_present,
            flagged_downstream=parents_present,
        ))
    return results

derived_feat    = evaluate_derived(feat_cols,    "int_team_season_features")
derived_context = evaluate_derived(context_cols, "int_team_season_context")

derived_all = pd.DataFrame(derived_feat + derived_context)

print("=== Q4 — Downstream / Derived Columns ===\n")
if len(derived_all):
    display(derived_all)
    flagged = derived_all[derived_all["flagged_downstream"]]
    print(f"\nTotal derived-column hits (parents present in same table): {len(flagged)}")
    for _, r in flagged.iterrows():
        print(f"  [{r['table']}] {r['derived_column']}  ←  "
              f"{r['parent_a']} {r['relationship']} {r['parent_b']}")
else:
    print("No matches from registry found — verify column names match actual DB schema.")

=== Q4 — Downstream / Derived Columns ===

,table,derived_column,relationship,parent_a,parent_b,parents_present,flagged_downstream
0,int_team_season_features,completion_pct,ratio,completions,pass_attempts,False,False
1,int_team_season_features,yards_per_attempt,ratio,pass_yards,pass_attempts,False,False
2,int_team_season_features,third_down_pct,ratio,third_down_conversions,third_down_attempts,True,True
3,int_team_season_features,fourth_down_pct,ratio,fourth_down_conversions,fourth_down_attempts,True,True
4,int_team_season_features,win_pct,ratio,wins,games_played,True,True
5,int_team_season_context,win_pct,ratio,wins,games_played,True,True

Total derived-column hits (parents present in same table): 4
  [int_team_season_features] third_down_pct  ←  third_down_conversions ratio third_down_attempts
  [int_team_season_features] fourth_down_pct  ←  fourth_down_conversions ratio fourth_down_attempts
  [int_team_season_features] win_pct  ←  wins ratio games_played
  [int_team_season_context] win_pct  ←  wins ratio games_played

In [10]:
# Cell 7 — Q5: Full candidate feature list
# ─────────────────────────────────────────
# Combines: (a) all columns across int tables, (b) duplication rulings,
# (c) derived-column flags into one flat table.
#
# Logic:
#   1. Start from raw_inventory.
#   2. For each (table, column) pair, look up its disposition from Q3.
#   3. Apply derived-column flags from Q4.
#   4. A column is kept (keep=True) if:
#        – not a join key (R1)
#        – is the authoritative copy (not superseded)
#        – not flagged as a downstream derived column
#   5. The authoritative_table for non-duplicated columns is the table
#      they live in.

# ── Step 1: resolve authoritative table for all columns ───────────────────
# Non-duplicated columns are authoritative in their own table by definition.
non_dup_cols = set(raw_inventory["column_name"]) - set(duplicated_names)

rows = []
for _, inv_row in raw_inventory.iterrows():
    col   = inv_row["column_name"]
    table = inv_row["table_name"]
    dtype = inv_row["data_type"]

    # ── Join keys ──────────────────────────────────────────────────────
    if col in JOIN_KEYS:
        rows.append(dict(
            column_name=col,
            authoritative_table="ALL (join key)",
            source_table=table,
            dtype=dtype,
            keep=False,
            reason_if_dropped="Join key — not a model feature",
        ))
        continue

    # ── Non-duplicated columns ────────────────────────────────────────
    if col in non_dup_cols:
        rows.append(dict(
            column_name=col,
            authoritative_table=table,
            source_table=table,
            dtype=dtype,
            keep=True,
            reason_if_dropped="",
        ))
        continue

    # ── Duplicated columns — look up ruling ───────────────────────────
    ruling = rulings_df[
        (rulings_df["column_name"] == col) & (rulings_df["table"] == table)
    ]
    if ruling.empty:
        auth  = table
        disp  = "KEEP — no ruling found (default)"
    else:
        auth  = ruling.iloc[0]["authoritative"]
        disp  = ruling.iloc[0]["disposition"]

    keep = ("KEEP" in disp) and ("DROP" not in disp)
    reason = "" if keep else disp

    rows.append(dict(
        column_name=col,
        authoritative_table=auth,
        source_table=table,
        dtype=dtype,
        keep=keep,
        reason_if_dropped=reason,
    ))

candidate_df = pd.DataFrame(rows)

# ── Step 2: apply derived-column flag ─────────────────────────────────────
# If a column is flagged as downstream in its authoritative table,
# flip keep → False and record reason.
if len(derived_all):
    flagged_derived = derived_all[derived_all["flagged_downstream"]][
        ["table", "derived_column", "parent_a", "parent_b"]
    ].copy()

    for _, dr in flagged_derived.iterrows():
        mask = (
            (candidate_df["column_name"] == dr["derived_column"]) &
            (candidate_df["authoritative_table"] == dr["table"]) &
            (candidate_df["keep"] == True)
        )
        candidate_df.loc[mask, "keep"] = False
        candidate_df.loc[mask, "reason_if_dropped"] = (
            f"Derived: {dr['parent_a']} / {dr['parent_b']} both present in {dr['table']}"
        )

# ── Step 3: deduplicate to one row per (authoritative_table, column_name) ─
# Drop the non-authoritative source_table rows — they have keep=False from
# Q3 rulings and are already captured in reason_if_dropped.
# For the final deliverable: one row per column_name (unique feature slot),
# keeping the keep=True rows and one keep=False row per name.

# Remove exact duplicate rows that arise from one column appearing in many
# tables — we keep one representative row per column_name.
# Priority: keep=True rows first, then keep=False.
candidate_final = (
    candidate_df
    .sort_values(["column_name", "keep"], ascending=[True, False])
    .drop_duplicates(subset=["column_name"], keep="first")
    .reset_index(drop=True)
    [["column_name", "authoritative_table", "dtype", "keep", "reason_if_dropped"]]
    .sort_values(["keep", "authoritative_table", "column_name"],
                 ascending=[False, True, True])
    .reset_index(drop=True)
)

# ── Summary ───────────────────────────────────────────────────────────────
n_keep = candidate_final["keep"].sum()
n_drop = (~candidate_final["keep"]).sum()
n_join = (candidate_final["authoritative_table"] == "ALL (join key)").sum()
n_derived = candidate_final["reason_if_dropped"].str.startswith("Derived:", na=False).sum()
n_dup_drop = candidate_final["reason_if_dropped"].str.startswith("DROP from candidate list", na=False).sum()

print("=" * 70)
print("  Q5 — CANDIDATE FEATURE LIST SUMMARY")
print("=" * 70)
print(f"  Total unique column names across int schema : {len(candidate_final)}")
print(f"  keep = True  (Day 8 starts from)            : {n_keep}")
print(f"  keep = False — join keys                    : {n_join}")
print(f"  keep = False — non-authoritative duplicates : {n_dup_drop}")
print(f"  keep = False — downstream derived columns   : {n_derived}")
print("=" * 70)
print()
display(candidate_final)

======================================================================
  Q5 — CANDIDATE FEATURE LIST SUMMARY
======================================================================
  Total unique column names across int schema : 162
  keep = True  (Day 8 starts from)            : 152
  keep = False — join keys                    : 7
  keep = False — non-authoritative duplicates : 1
  keep = False — downstream derived columns   : 2
======================================================================

,column_name,authoritative_table,dtype,keep,reason_if_dropped
0,away_elevation_ascent_ft,int_game_environment,double precision,True,
1,away_elevation_delta_ft,int_game_environment,double precision,True,
2,away_home_elevation_ft,int_game_environment,double precision,True,
3,away_travel_distance_mi,int_game_environment,numeric,True,
4,away_tz_delta_hrs,int_game_environment,integer,True,
5,humidity_pct,int_game_environment,smallint,True,
6,is_dome,int_game_environment,boolean,True,
7,is_dome_adjusted_weather,int_game_environment,boolean,True,
8,is_high_wind,int_game_environment,boolean,True,
9,is_precipitation,int_game_environment,boolean,True,
10,precipitation_inches,int_game_environment,numeric,True,
11,temperature_f,int_game_environment,numeric,True,
12,venue_elevation_ft,int_game_environment,double precision,True,
13,venue_id,int_game_environment,bigint,True,
14,wind_gusts_mph,int_game_environment,numeric,True,
15,wind_speed_mph,int_game_environment,numeric,True,
16,close_game_epa_per_play,int_game_team_features,numeric,True,
17,close_game_play_count,int_game_team_features,bigint,True,
18,days_since_last_game,int_game_team_features,integer,True,
19,def_epa_per_play_allowed,int_game_team_features,numeric,True,
20,game_script,int_game_team_features,text,True,
21,game_script_avg_margin,int_game_team_features,numeric,True,
22,last3_def_epa_avg,int_game_team_features,numeric,True,
23,last3_off_epa_avg,int_game_team_features,numeric,True,
24,last3_points_allowed_avg,int_game_team_features,numeric,True,
25,last3_points_scored_avg,int_game_team_features,numeric,True,
26,last3_win_pct,int_game_team_features,numeric,True,
27,opp_sp_rating_at_game_time,int_game_team_features,numeric,True,
28,opponent,int_game_team_features,text,True,
29,points_allowed,int_game_team_features,integer,True,
30,points_scored,int_game_team_features,integer,True,
31,win,int_game_team_features,integer,True,
32,close_game_count,int_team_season_context,bigint,True,
33,close_game_count_plays_based,int_team_season_context,bigint,True,
34,close_game_epa_per_play_season_avg,int_team_season_context,numeric,True,
35,close_game_plays_total,int_team_season_context,numeric,True,
36,off_epa_total_per_game,int_team_season_context,numeric,True,
37,off_third_down_conv_rate,int_team_season_context,numeric,True,
38,pct_games_comfortable,int_team_season_context,numeric,True,
39,pct_games_competitive,int_team_season_context,numeric,True,
40,pct_games_deficit,int_team_season_context,numeric,True,
41,pct_games_dominant,int_team_season_context,numeric,True,
42,pct_games_large_deficit,int_team_season_context,numeric,True,
43,penalties_per_game,int_team_season_context,numeric,True,
44,penalty_yards_per_game,int_team_season_context,numeric,True,
45,plays_per_game,int_team_season_context,numeric,True,
46,rush_rate,int_team_season_context,numeric,True,
47,sacks_per_game,int_team_season_context,numeric,True,
48,scoring_efficiency_ratio,int_team_season_context,numeric,True,
49,tfl_per_game,int_team_season_context,numeric,True,
50,turnover_margin_per_game,int_team_season_context,numeric,True,
51,turnovers_forced_per_game,int_team_season_context,numeric,True,
52,turnovers_lost_per_game,int_team_season_context,numeric,True,
53,avg_point_diff,int_team_season_features,numeric,True,
54,avg_points_allowed,int_team_season_features,numeric,True,
55,avg_points_scored,int_team_season_features,numeric,True,
56,away_games,int_team_season_features,bigint,True,
57,city,int_team_season_features,text,True,
58,completion_pct,int_team_season_features,numeric,True,
59,conference,int_team_season_features,text,True,
60,current_class_rank,int_team_season_features,integer,True,
61,def_drives,int_team_season_features,integer,True,
62,def_epa_per_play,int_team_season_features,numeric,True,
63,def_epa_total,int_team_season_features,numeric,True,
64,def_explosiveness,int_team_season_features,numeric,True,
65,def_field_position_avg_start,int_team_season_features,numeric,True,
66,def_field_position_predicted_pts,int_team_season_features,numeric,True,
67,def_havoc_db,int_team_season_features,numeric,True,
68,def_havoc_front_seven,int_team_season_features,numeric,True,
69,def_havoc_total,int_team_season_features,numeric,True,
70,def_line_yards,int_team_season_features,numeric,True,
71,def_open_field_yards,int_team_season_features,numeric,True,
72,def_pass_downs_epa,int_team_season_features,numeric,True,
73,def_pass_downs_success_rate,int_team_season_features,numeric,True,
74,def_pass_success_rate,int_team_season_features,numeric,True,
75,def_passing_epa,int_team_season_features,numeric,True,
76,def_plays,int_team_season_features,integer,True,
77,def_power_success,int_team_season_features,numeric,True,
78,def_pts_per_opp,int_team_season_features,numeric,True,
79,def_rush_success_rate,int_team_season_features,numeric,True,
80,def_rushing_epa,int_team_season_features,numeric,True,
81,def_second_level_yards,int_team_season_features,numeric,True,
82,def_std_downs_epa,int_team_season_features,numeric,True,
83,def_std_downs_success_rate,int_team_season_features,numeric,True,
84,def_stuff_rate,int_team_season_features,numeric,True,
85,def_success_rate,int_team_season_features,numeric,True,
86,epa_differential,int_team_season_features,numeric,True,
87,fourth_down_attempts,int_team_season_features,integer,True,
88,fourth_down_conversions,int_team_season_features,integer,True,
89,fumbles_lost,int_team_season_features,integer,True,
90,fumbles_recovered,int_team_season_features,integer,True,
91,games_played,int_team_season_features,bigint,True,
92,home_games,int_team_season_features,bigint,True,
93,interceptions_gained,int_team_season_features,integer,True,
94,interceptions_thrown,int_team_season_features,integer,True,
95,latitude,int_team_season_features,numeric,True,
96,longitude,int_team_season_features,numeric,True,
97,losses,int_team_season_features,bigint,True,
98,neutral_site_games,int_team_season_features,bigint,True,
99,off_drives,int_team_season_features,integer,True,
100,off_epa_per_play,int_team_season_features,numeric,True,
101,off_epa_total,int_team_season_features,numeric,True,
102,off_explosiveness,int_team_season_features,numeric,True,
103,off_field_position_avg_start,int_team_season_features,numeric,True,
104,off_field_position_predicted_pts,int_team_season_features,numeric,True,
105,off_line_yards,int_team_season_features,numeric,True,
106,off_open_field_yards,int_team_season_features,numeric,True,
107,off_pass_downs_epa,int_team_season_features,numeric,True,
108,off_pass_downs_success_rate,int_team_season_features,numeric,True,
109,off_pass_success_rate,int_team_season_features,numeric,True,
110,off_passing_epa,int_team_season_features,numeric,True,
111,off_plays,int_team_season_features,integer,True,
112,off_power_success,int_team_season_features,numeric,True,
113,off_pts_per_opp,int_team_season_features,numeric,True,
114,off_rush_success_rate,int_team_season_features,numeric,True,
115,off_rushing_epa,int_team_season_features,numeric,True,
116,off_second_level_yards,int_team_season_features,numeric,True,
117,off_std_downs_epa,int_team_season_features,numeric,True,
118,off_std_downs_success_rate,int_team_season_features,numeric,True,
119,off_stuff_rate,int_team_season_features,numeric,True,
120,off_success_rate,int_team_season_features,numeric,True,
121,pass_attempts,int_team_season_features,integer,True,
122,pass_completions,int_team_season_features,integer,True,
123,pass_tds,int_team_season_features,integer,True,
124,passing_yards,int_team_season_features,numeric,True,
125,penalties,int_team_season_features,integer,True,
126,penalty_yards,int_team_season_features,numeric,True,
127,recruiting_3yr_avg,int_team_season_features,numeric,True,
128,rush_attempts,int_team_season_features,integer,True,
129,rush_tds,int_team_season_features,integer,True,
130,rushing_yards,int_team_season_features,numeric,True,
131,sacks,int_team_season_features,integer,True,
132,sp_defense,int_team_season_features,numeric,True,
133,sp_defense_ranking,int_team_season_features,integer,True,
134,sp_offense,int_team_season_features,numeric,True,
135,sp_offense_ranking,int_team_season_features,integer,True,
136,sp_ranking,int_team_season_features,integer,True,
137,sp_rating,int_team_season_features,numeric,True,
138,sp_special_teams,int_team_season_features,numeric,True,
139,stat_games,int_team_season_features,integer,True,
140,state,int_team_season_features,text,True,
141,tackles_for_loss,int_team_season_features,integer,True,
142,team_name,int_team_season_features,text,True,
143,third_down_attempts,int_team_season_features,integer,True,
144,third_down_conversions,int_team_season_features,integer,True,
145,timezone,int_team_season_features,text,True,
146,total_yards,int_team_season_features,numeric,True,
147,turnovers,int_team_season_features,integer,True,
148,wins,int_team_season_features,bigint,True,
149,yards_per_attempt,int_team_season_features,numeric,True,
150,elevation_feet,venue_elevations,double precision,True,
151,venue_name,venue_elevations,text,True,
152,away_team,ALL (join key),text,False,Join key — not a model feature
153,game_date,ALL (join key),date,False,Join key — not a model feature
154,game_id,ALL (join key),bigint,False,Join key — not a model feature
155,home_team,ALL (join key),text,False,Join key — not a model feature
156,season,ALL (join key),integer,False,Join key — not a model feature
157,team_id,ALL (join key),integer,False,Join key — not a model feature
158,week,ALL (join key),integer,False,Join key — not a model feature
159,fourth_down_pct,int_team_season_features,numeric,False,Derived: fourth_down_conversions / fourth_down_attempts ...
160,third_down_pct,int_team_season_features,numeric,False,Derived: third_down_conversions / third_down_attempts bo...
161,win_pct,int_team_season_features,numeric,False,DROP from candidate list — superseded by int_team_season...

In [11]:
# Cell 8 — Write artifact and print Day 8 start count
# ─────────────────────────────────────────────────────
import os

artifact_path = os.path.expanduser("~/cfb-analytics/artifacts/candidate_features.csv")
os.makedirs(os.path.dirname(artifact_path), exist_ok=True)

candidate_final.to_csv(artifact_path, index=False)

# Confirm file written
size_kb = os.path.getsize(artifact_path) / 1024
print(f"✓  candidate_features.csv written to: {artifact_path}")
print(f"   File size: {size_kb:.1f} KB   |   Rows: {len(candidate_final)}")
print()

# ── Final locked count ────────────────────────────────────────────────────
keep_cols = candidate_final[candidate_final["keep"] == True]
print("=" * 70)
print(f"  DAY 7 LOCKED — Day 8 candidate feature count: {len(keep_cols)}")
print("=" * 70)
print()
print("Kept features by authoritative table:")
print(keep_cols.groupby("authoritative_table").size().rename("n_kept").to_string())
print()
print("Full keep=True list:")
display(keep_cols[["column_name", "authoritative_table", "dtype"]].reset_index(drop=True))

✓  candidate_features.csv written to: /Users/kevinjohnson/cfb-analytics/artifacts/candidate_features.csv
   File size: 9.2 KB   |   Rows: 162

======================================================================
  DAY 7 LOCKED — Day 8 candidate feature count: 152
======================================================================

Kept features by authoritative table:
authoritative_table
int_game_environment        16
int_game_team_features      16
int_team_season_context     21
int_team_season_features    97
venue_elevations             2

Full keep=True list:

                            column_name       authoritative_table             dtype
0              away_elevation_ascent_ft      int_game_environment  double precision
1               away_elevation_delta_ft      int_game_environment  double precision
2                away_home_elevation_ft      int_game_environment  double precision
3               away_travel_distance_mi      int_game_environment           numeric
4                     away_tz_delta_hrs      int_game_environment           integer
5                          humidity_pct      int_game_environment          smallint
6                               is_dome      int_game_environment           boolean
7              is_dome_adjusted_weather      int_game_environment           boolean
8                          is_high_wind      int_game_environment           boolean
9                      is_precipitation      int_game_environment           boolean
10                 precipitation_inches      int_game_environment           numeric
11                        temperature_f      int_game_environment           numeric
12                   venue_elevation_ft      int_game_environment  double precision
13                             venue_id      int_game_environment            bigint
14                       wind_gusts_mph      int_game_environment           numeric
15                       wind_speed_mph      int_game_environment           numeric
16              close_game_epa_per_play    int_game_team_features           numeric
17                close_game_play_count    int_game_team_features            bigint
18                 days_since_last_game    int_game_team_features           integer
19             def_epa_per_play_allowed    int_game_team_features           numeric
20                          game_script    int_game_team_features              text
21               game_script_avg_margin    int_game_team_features           numeric
22                    last3_def_epa_avg    int_game_team_features           numeric
23                    last3_off_epa_avg    int_game_team_features           numeric
24             last3_points_allowed_avg    int_game_team_features           numeric
25              last3_points_scored_avg    int_game_team_features           numeric
26                        last3_win_pct    int_game_team_features           numeric
27           opp_sp_rating_at_game_time    int_game_team_features           numeric
28                             opponent    int_game_team_features              text
29                       points_allowed    int_game_team_features           integer
30                        points_scored    int_game_team_features           integer
31                                  win    int_game_team_features           integer
32                     close_game_count   int_team_season_context            bigint
33         close_game_count_plays_based   int_team_season_context            bigint
34   close_game_epa_per_play_season_avg   int_team_season_context           numeric
35               close_game_plays_total   int_team_season_context           numeric
36               off_epa_total_per_game   int_team_season_context           numeric
37             off_third_down_conv_rate   int_team_season_context           numeric
38                pct_games_comfortable   int_team_season_context           numeric
39                pct_games_competitive   int_team_season_context           numeric
40                    pct_games_deficit   int_team_season_context           numeric
41                   pct_games_dominant   int_team_season_context           numeric
42              pct_games_large_deficit   int_team_season_context           numeric
43                   penalties_per_game   int_team_season_context           numeric
44               penalty_yards_per_game   int_team_season_context           numeric
45                       plays_per_game   int_team_season_context           numeric
46                            rush_rate   int_team_season_context           numeric
47                       sacks_per_game   int_team_season_context           numeric
48             scoring_efficiency_ratio   int_team_season_context           numeric
49                         tfl_per_game   int_team_season_context           numeric
50             turnover_margin_per_game   int_team_season_context           numeric
51            turnovers_forced_per_game   int_team_season_context           numeric
52              turnovers_lost_per_game   int_team_season_context           numeric
53                       avg_point_diff  int_team_season_features           numeric
54                   avg_points_allowed  int_team_season_features           numeric
55                    avg_points_scored  int_team_season_features           numeric
56                           away_games  int_team_season_features            bigint
57                                 city  int_team_season_features              text
58                       completion_pct  int_team_season_features           numeric
59                           conference  int_team_season_features              text
60                   current_class_rank  int_team_season_features           integer
61                           def_drives  int_team_season_features           integer
62                     def_epa_per_play  int_team_season_features           numeric
63                        def_epa_total  int_team_season_features           numeric
64                    def_explosiveness  int_team_season_features           numeric
65         def_field_position_avg_start  int_team_season_features           numeric
66     def_field_position_predicted_pts  int_team_season_features           numeric
67                         def_havoc_db  int_team_season_features           numeric
68                def_havoc_front_seven  int_team_season_features           numeric
69                      def_havoc_total  int_team_season_features           numeric
70                       def_line_yards  int_team_season_features           numeric
71                 def_open_field_yards  int_team_season_features           numeric
72                   def_pass_downs_epa  int_team_season_features           numeric
73          def_pass_downs_success_rate  int_team_season_features           numeric
74                def_pass_success_rate  int_team_season_features           numeric
75                      def_passing_epa  int_team_season_features           numeric
76                            def_plays  int_team_season_features           integer
77                    def_power_success  int_team_season_features           numeric
78                      def_pts_per_opp  int_team_season_features           numeric
79                def_rush_success_rate  int_team_season_features           numeric
80                      def_rushing_epa  int_team_season_features           numeric
81               def_second_level_yards  int_team_season_features           numeric
82                    def_std_downs_epa  int_team_season_features           numeric
83           def_std_downs_success_rate  int_team_season_features           numeric
84                       def_stuff_rate  int_team_season_features           numeric
85                     def_success_rate  int_team_season_features           numeric
86                     epa_differential  int_team_season_features           numeric
87                 fourth_down_attempts  int_team_season_features           integer
88              fourth_down_conversions  int_team_season_features           integer
89                         fumbles_lost  int_team_season_features           integer
90                    fumbles_recovered  int_team_season_features           integer
91                         games_played  int_team_season_features            bigint
92                           home_games  int_team_season_features            bigint
93                 interceptions_gained  int_team_season_features           integer
94                 interceptions_thrown  int_team_season_features           integer
95                             latitude  int_team_season_features           numeric
96                            longitude  int_team_season_features           numeric
97                               losses  int_team_season_features            bigint
98                   neutral_site_games  int_team_season_features            bigint
99                           off_drives  int_team_season_features           integer
100                    off_epa_per_play  int_team_season_features           numeric
101                       off_epa_total  int_team_season_features           numeric
102                   off_explosiveness  int_team_season_features           numeric
103        off_field_position_avg_start  int_team_season_features           numeric
104    off_field_position_predicted_pts  int_team_season_features           numeric
105                      off_line_yards  int_team_season_features           numeric
106                off_open_field_yards  int_team_season_features           numeric
107                  off_pass_downs_epa  int_team_season_features           numeric
108         off_pass_downs_success_rate  int_team_season_features           numeric
109               off_pass_success_rate  int_team_season_features           numeric
110                     off_passing_epa  int_team_season_features           numeric
111                           off_plays  int_team_season_features           integer
112                   off_power_success  int_team_season_features           numeric
113                     off_pts_per_opp  int_team_season_features           numeric
114               off_rush_success_rate  int_team_season_features           numeric
115                     off_rushing_epa  int_team_season_features           numeric
116              off_second_level_yards  int_team_season_features           numeric
117                   off_std_downs_epa  int_team_season_features           numeric
118          off_std_downs_success_rate  int_team_season_features           numeric
119                      off_stuff_rate  int_team_season_features           numeric
120                    off_success_rate  int_team_season_features           numeric
121                       pass_attempts  int_team_season_features           integer
122                    pass_completions  int_team_season_features           integer
123                            pass_tds  int_team_season_features           integer
124                       passing_yards  int_team_season_features           numeric
125                           penalties  int_team_season_features           integer
126                       penalty_yards  int_team_season_features           numeric
127                  recruiting_3yr_avg  int_team_season_features           numeric
128                       rush_attempts  int_team_season_features           integer
129                            rush_tds  int_team_season_features           integer
130                       rushing_yards  int_team_season_features           numeric
131                               sacks  int_team_season_features           integer
132                          sp_defense  int_team_season_features           numeric
133                  sp_defense_ranking  int_team_season_features           integer
134                          sp_offense  int_team_season_features           numeric
135                  sp_offense_ranking  int_team_season_features           integer
136                          sp_ranking  int_team_season_features           integer
137                           sp_rating  int_team_season_features           numeric
138                    sp_special_teams  int_team_season_features           numeric
139                          stat_games  int_team_season_features           integer
140                               state  int_team_season_features              text
141                    tackles_for_loss  int_team_season_features           integer
142                           team_name  int_team_season_features              text
143                 third_down_attempts  int_team_season_features           integer
144              third_down_conversions  int_team_season_features           integer
145                            timezone  int_team_season_features              text
146                         total_yards  int_team_season_features           numeric
147                           turnovers  int_team_season_features           integer
148                                wins  int_team_season_features            bigint
149                   yards_per_attempt  int_team_season_features           numeric
150                      elevation_feet          venue_elevations  double precision
151                          venue_name          venue_elevations              text

In [12]:
# Cell 9 — Dropped-column audit (sanity check)
# ─────────────────────────────────────────────
# Review every dropped column so nothing is lost silently.

dropped = candidate_final[candidate_final["keep"] == False].copy()

print(f"Total dropped: {len(dropped)}\n")

# Group 1: join keys
jk = dropped[dropped["authoritative_table"] == "ALL (join key)"]
print(f"── Join keys ({len(jk)}) ──────────────────────────")
print(jk[["column_name", "authoritative_table"]].to_string(index=False))

# Group 2: non-authoritative duplicates
nd = dropped[dropped["reason_if_dropped"].str.startswith("DROP from candidate", na=False)]
print(f"\n── Non-authoritative duplicate copies ({len(nd)}) ──────────────────────")
print(nd[["column_name", "authoritative_table", "reason_if_dropped"]].to_string(index=False))

# Group 3: derived columns
dv = dropped[dropped["reason_if_dropped"].str.startswith("Derived:", na=False)]
print(f"\n── Downstream derived columns ({len(dv)}) ──────────────────────────────")
print(dv[["column_name", "reason_if_dropped"]].to_string(index=False))

# Group 4: anything else
other = dropped[
    ~dropped["authoritative_table"].eq("ALL (join key)") &
    ~dropped["reason_if_dropped"].str.startswith("DROP from candidate", na=False) &
    ~dropped["reason_if_dropped"].str.startswith("Derived:", na=False)
]
if len(other):
    print(f"\n── Other dropped ({len(other)}) ───────────────────────────────────────")
    display(other)

print("\n── END OF DAY 7 ──────────────────────────────────────────────────────")

Total dropped: 10

── Join keys (7) ──────────────────────────
column_name authoritative_table
  away_team      ALL (join key)
  game_date      ALL (join key)
    game_id      ALL (join key)
  home_team      ALL (join key)
     season      ALL (join key)
    team_id      ALL (join key)
       week      ALL (join key)

── Non-authoritative duplicate copies (1) ──────────────────────
column_name      authoritative_table                                                 reason_if_dropped
    win_pct int_team_season_features DROP from candidate list — superseded by int_team_season_features

── Downstream derived columns (2) ──────────────────────────────
    column_name                                                                                reason_if_dropped
fourth_down_pct Derived: fourth_down_conversions / fourth_down_attempts both present in int_team_season_features
 third_down_pct   Derived: third_down_conversions / third_down_attempts both present in int_team_season_features

── END OF DAY 7 ──────────────────────────────────────────────────────